### ISSUE TITLE
a few issues

### ISSUE THREAD

**Issue by AlpTheTurkic** [textGamex/Moder#10]
I click to change it to Turkish or English and it doesn't work. Why?

**Comment by textGamex** [comment]
You need to reopen the tab after changing the language settings.
 
The language setting only controls which localization folder the game reads text from; the software itself currently supports only Chinese.

**Comment by textGamex** [comment]
> I also clicked on the place where I clicked to select the game folder, but it does not open.

Are you referring to the dialog not popping up?

**Comment by textGamex** [comment]
I'm not sure why the selection dialog isn't appearing, but if you'd like to set the directory, please click the button on the left.
![image](https://github.com/user-attachments/assets/70cddd52-de5e-4bf0-a9b4-81d603caf7ee)

**Comment by textGamex** [comment]
Have your issues been resolved?

**Comment by textGamex** [comment]
It looks like you do not know WinUI development, right?

**Comment by textGamex** [comment]
I can release a version that I compiled later.

**Comment by textGamex** [comment]
Ok, I have already released it.

**Comment by textGamex** [comment]
Is it working properly now?

**Comment by textGamex** [comment]
> ![image](https://private-user-images.githubusercontent.com/85740450/384890177-74241ec1-d3bd-45ac-b8f3-a1038e228e48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjI3MzgsIm5iZiI6MTczMTMyMjQzOCwicGF0aCI6Ii84NTc0MDQ1MC8zODQ4OTAxNzctNzQyNDFlYzEtZDNiZC00NWFjLWI4ZjMtYTEwMzhlMjI4ZTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDEwNTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZTQwMDI4NjI2NDk0NWFkNTlhNmQ4ODFkOTI1M2YwYmY2ZWQzZDFhMjUwOTk3MDg0MzQ2MjkzNGQyMDkwZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7L1spa_8NGNde9C3pJ5yu5d-PJQGjRHnhr_Y0_XWJBE) Do I click on this? If I click on this, it opens but those buttons still do not work.

yes
I'm not sure why the button is still not working, I wonder if it might be because your Windows version is too low?

**Comment by textGamex** [comment]
My friend also used this software, and he didn't have this issue

**Comment by textGamex** [comment]
You can record the process as a video

**Comment by textGamex** [comment]
According to Microsoft's official documentation, the minimum requirement for WinUI is Windows 10 1809 - Build 17763 or newer.

**Comment by textGamex** [comment]
oh，let me test it on my computer

**Comment by textGamex** [comment]
I think I need to spend some time investigating the cause.

**Comment by textGamex** [comment]
I'm sorry for taking up so much of your time

**Comment by textGamex** [comment]
I wrote a test app for pop-up windows. Could you download it and test whether the pop-up displays correctly?

[OneDrive](https://1drv.ms/u/c/8eec4762c9334469/EeCLr_ai9rZCijTYfW5k-hoBlgGu5Mqm4rJL0qn9yEDohQ?e=Nl976v)

**Comment by textGamex** [comment]
Sorry, I don't understand Turkish. What does this sentence mean in English?

**Comment by textGamex** [comment]
I have tried to fix it. You can download the source code, compile it, and run it to test it out.
[ButtonTestAppCode.zip](https://github.com/user-attachments/files/17892671/ButtonTestApp.zip)

**Comment by textGamex** [comment]
Like the Moder project

**Comment by textGamex** [comment]
I have tried to fix it. You can download the latest source code for the Moder project, compile it, and run it to test it out.

**Comment by textGamex** [comment]
> ![image](https://private-user-images.githubusercontent.com/85740450/389274878-d3f15d97-9edb-40ec-ac57-73ed969418d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTQxNDksIm5iZiI6MTczMjQ1Mzg0OSwicGF0aCI6Ii84NTc0MDQ1MC8zODkyNzQ4NzgtZDNmMTVkOTctOWVkYi00MGVjLWFjNTctNzNlZDk2OTQxOGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDEzMTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1Zjk4MDBhZDBmOTBhMGYwNjA5ZGRmYzY1YTkxYzdmODZiM2ZjZTE0ZWEyMzVlYmEyZDNhZjM1ZmQ2NzYzZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.phXwRS_-Sncdey2c5SLItsJBR2LHnGzY1tXhbpxdSsM) Is it normal for it to appear this color?

Do you mean the background?

**Comment by textGamex** [comment]
>this thing has also gone into a loop.

This is a bug, and I have just fixed it.

**Comment by textGamex** [comment]
>The buttons in the second image are now working. What should I do now?

Using this software? Currently, you can only edit state files and use a half-finished character editor.

**Comment by textGamex** [comment]
I am considering whether to add localization support for the software. However, my English is poor, and I initially thought that most users of Moder would be Chinese (since I only promoted it on Chinese video websites). I didn't expect the first person to report a bug to be a foreigner😄.

**Comment by textGamex** [comment]
It looks like an IDE error message

**Comment by textGamex** [comment]
Let's focus on feature development for now. I can start by localizing the README file into English.

**Comment by textGamex** [comment]
Once I have completed the character editor, I can consider working on localization.
